/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#1c1b1d',
        'tertiary-fixed-dim': '#4edea3',
        'surface-tint': '#00e55b',
        'on-secondary-fixed': '#00210d',
        'tertiary-fixed': '#6ffbbe',
        'surface-container-lowest': '#0e0e10',
        'secondary-container': '#02f084',
        'secondary-fixed': '#5eff9c',
        'on-surface-variant': '#b9ccb5',
        'surface-container': '#201f21',
        'on-tertiary': '#003824',
        'on-primary-container': '#007128',
        'on-background': '#e5e1e4',
        'on-primary-fixed-variant': '#00531b',
        'on-surface': '#e5e1e4',
        'on-error': '#690005',
        'primary': '#edffe8',
        'on-secondary-fixed-variant': '#005229',
        'on-tertiary-container': '#006f4c',
        'on-secondary-container': '#006836',
        'outline-variant': '#3b4b3a',
        'tertiary': '#eafff0',
        'tertiary-container': '#69f6b9',
        'secondary-fixed-dim': '#00e37d',
        'error': '#ffb4ab',
        'surface': '#131315',
        'error-container': '#93000a',
        'surface-container-high': '#2a2a2c',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-fixed': '#002107',
        'primary-fixed': '#6bff83',
        'secondary': '#b4ffc5',
        'background': '#131315',
        'inverse-surface': '#e5e1e4',
        'surface-container-highest': '#353437',
        'outline': '#849581',
        'inverse-primary': '#006e27',
        'primary-container': '#00ff66',
        'surface-bright': '#39393b',
        'on-secondary': '#00391b',
        'on-primary': '#003911',
        'on-tertiary-fixed': '#002113',
        'surface-dim': '#131315',
        'surface-variant': '#353437',
        'inverse-on-surface': '#313032',
        'primary-fixed-dim': '#00e55b',
        'on-error-container': '#ffdad6'
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px'
      },
      spacing: {
        'margin': '2rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2rem',
        'space-xs': '0.25rem',
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'gutter': '1.5rem',
        'space-xl': '2.5rem',
        'margin-lg': '4rem',
        'margin-sm': '1rem'
      },
      fontFamily: {
        'label-lg': ['Space Mono', 'monospace'],
        'headline-md': ['Syne', 'sans-serif'],
        'headline-lg-mobile': ['Syne', 'sans-serif'],
        'body-sm': ['Space Mono', 'monospace'],
        'headline-lg': ['Syne', 'sans-serif'],
        'headline-xl-mobile': ['Syne', 'sans-serif'],
        'label-md': ['Space Mono', 'monospace'],
        'headline-xl': ['Syne', 'sans-serif'],
        'body-lg': ['Space Mono', 'monospace'],
        'body-md': ['Space Mono', 'monospace'],
        'label-sm': ['Space Mono', 'monospace'],
        'headline-sm': ['Syne', 'sans-serif']
      },
      fontSize: {
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.06em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-md': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }]
      }
    }
  }
}
